services:
  - type: web
    name: edinyy-reestr
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_LOGIN
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
